CREATE TABLE TUSUARIO (
	ID VARCHAR(300), 
	NAME VARCHAR(300), 
	EMAIL VARCHAR(300), 
	PASSWORD VARCHAR(300), 
	FECHA_CREACION VARCHAR(20), 
	LAST_LOGIN VARCHAR(20), 
	FECHA_MODIFICACION VARCHAR(20), 
	ESTADO_USUARIO VARCHAR(20), 
	TOKEN VARCHAR(100)
);
CREATE TABLE TUSUARIOPHONES (	
  	ID VARCHAR(300), 
	ITEM INTEGER, 
	NUMERO VARCHAR(20), 
	CODIGO_CITY VARCHAR(20), 
	CODIGO_PAIS VARCHAR(20)
); 